// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_yBG_7Mw-3bgOVHm5dOHTOa8UnQnm4pw',
    appId: '1:253897407965:web:59401322d3770929374a34',
    messagingSenderId: '253897407965',
    projectId: 'flutterprojects-3d7c5',
    authDomain: 'flutterprojects-3d7c5.firebaseapp.com',
    storageBucket: 'flutterprojects-3d7c5.appspot.com',
    measurementId: 'G-N2SXF2HWBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyN4uVusqwxCnyXmBcbsMrvNhooAanXA8',
    appId: '1:253897407965:android:4065437a0310996e374a34',
    messagingSenderId: '253897407965',
    projectId: 'flutterprojects-3d7c5',
    storageBucket: 'flutterprojects-3d7c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU1VqXkL4A_HoO8AhNbtWKC2xXg0f5SY0',
    appId: '1:253897407965:ios:f880524d8ce520bd374a34',
    messagingSenderId: '253897407965',
    projectId: 'flutterprojects-3d7c5',
    storageBucket: 'flutterprojects-3d7c5.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU1VqXkL4A_HoO8AhNbtWKC2xXg0f5SY0',
    appId: '1:253897407965:ios:f880524d8ce520bd374a34',
    messagingSenderId: '253897407965',
    projectId: 'flutterprojects-3d7c5',
    storageBucket: 'flutterprojects-3d7c5.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_yBG_7Mw-3bgOVHm5dOHTOa8UnQnm4pw',
    appId: '1:253897407965:web:f8c368399dfd1240374a34',
    messagingSenderId: '253897407965',
    projectId: 'flutterprojects-3d7c5',
    authDomain: 'flutterprojects-3d7c5.firebaseapp.com',
    storageBucket: 'flutterprojects-3d7c5.appspot.com',
    measurementId: 'G-JGEGGPHP95',
  );
}
